### ISSUE TITLE
Any specific reason for executing a new shell upon changing dir?

### ISSUE THREAD

**Issue by akashagarwal7** [yankeexe/git-worktree-switcher#2]
Title basically. Executing a new shell doesn't let you easily switch back the directory/worktree with `cd -` if you'd like to. Also, people like me have a lot of things going on in `~/.profile` which take about 2 seconds on each shell execution. Not ideal.

Edit- forgot to add my appreciation for sharing the tool. Thanks heaps!

**Comment by yankeexe** [comment]
Hey @akashagarwal7, you are right, executing a new shell doesn't let you easily switch back using `cd -`, so for that, there's a sub-command in the tool `wt -` which takes you to the main worktree. But again, what if you are switching from one worktree to the next? Well for that you can use `wt <worktree-name>` to jump around.

The reason for needing to execute a new shell is because the script is run on a sub-shell (fork of the main shell) and when you want to `cd` into some directory using shell script, it's only possible if you replace the main shell with the sub-shell the script is running on.

If you find some solutions around it, happy to integrate it to the tool :slightly_smiling_face:

**Comment by akashagarwal7** [comment]
Ah you beat me to it. Been out of touch with bash and I found out the same! The probable alternative here is to source the file and declare commands like `wt -` as one-worded functions. For two or more worded commands like `wt -` itself, you'd still source the file with `wt()` being a declared, [wrapper function](https://stackoverflow.com/a/10169840/5157706).

Edit- Here's an [example](https://stackoverflow.com/a/12423064/5157706) of functions working successfully to switch directories :)

**Comment by yankeexe** [comment]
I am not sure how the implementation would be like using `.bashrc` or other configs here. Can you provide a sample maybe to make it clear in context of `wt` :slightly_smiling_face:

**Comment by akashagarwal7** [comment]
I've got something working locally, I'll submit a PR later. Probably worth another issue, but something that doesn't work reliably is worktrees containing a slash in their name.
```
awk: syntax error at source line 1
 context is
        /new/pvc-debugger/ >>>  { <<< 
awk: bailing out at source line 1
```
